project:
  type: website

website:
  title: "Izar de Villasante"
  site-url: https://www.idevillasante.com
  navbar:
    right:
      - text: Blog
        href: Blog.qmd 
      - icon: github
        href: https://github.com/izarvillasante
      - icon: twitter
        href: https://twitter.com
      - text: "<F.A.I.R.>" 
        href: posts/FAIR/index.qmd
#########################
# You can ignore this part in the first step
      - icon: rss
        href: blog.xml
      - text: Resources
        menu:
          - text: Workshops
            href: https://ijcbit.github.io/Workshops/

      - text: Archive
        href: archive.qmd
  google-analytics: G-V60NC304KY
  cookie-consent: true
  # twitter-card: 
  #   image: thumbnail_blog.png
  #   card-style: summary_large_image
  #   creator: "@izar"

# filters:
  # - code-filename
######################### 

format:
  html:
    theme:
      light: theme.scss
      dark: darkly
      
    css: styles.css



