---
title: "FAIR presentation"
author: "Izar de Villasante"
date: "2022-12-22"
categories: [news]
---

This list should contain a series of topics related to modern data science working environment with R. You can expect posts related to making your work FAIR:

-   Findable:

    -   How to publish your work (blog, book, revealjs presentations, webpages, github, CRAN/bioconductor)

-   Accessible:

    -   How to manage access to your work and how to access it using api.

-   Interoperable:

    -   Make your work interact with other tools & programs.

    -   Workflow languages (nextflow, targets...)

    -   YAML language and parameters.

    -   Quarto extensions

-   Reproducible:

    1.  Running R and Rstudio from anywhere with any computer, at any time.

        -   Using and customising rocker-project containers.

        -   Setting up binder to start developing right from your github repository.

        -   Using github registry to store your docker/singularity containers.

    2.  DevOps principles and practices for bioinformatics.

        -   Automatically install new packages with renv and github actions

        -   Set up a CI system with github actions and github registry to keep your work ready for publication/packaging

        -   Metadata & best practices for coding.

Below is a presentation with some of the main concepts that inspired this series.

<div>

```{=html}
<iframe width="780" height="500" class="slide-deck" src="../../slides/press.html"></iframe>
```

</div>
