name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: " Wellcome to the blog repo, please make sure you add new pages under the posts folder and add publish: false until the document is ready "
        pr-message: "Feel free to use this blog as template"
